export const sampleDomains = [
  {
    id: 1,
    name: "venture.co",
    price: "$45,000",
    category: "premium",
    status: "available",
    length: 7,
    extension: ".co",
    popularity: 95,
    isPremium: true,
    isLuxury: false,
    isShort: false,
    isBrandable: false
  },
  {
    id: 2,
    name: "nexus.io",
    price: "$35,000",
    category: "premium",
    status: "available",
    length: 5,
    extension: ".io",
    popularity: 88,
    isPremium: true,
    isLuxury: false,
    isShort: true,
    isBrandable: false
  },
  {
    id: 3,
    name: "luxe.com",
    price: "$125,000",
    category: "luxury",
    status: "available",
    length: 4,
    extension: ".com",
    popularity: 92,
    isPremium: false,
    isLuxury: true,
    isShort: true,
    isBrandable: false
  },
  {
    id: 4,
    name: "ai.tech",
    price: "$55,000",
    category: "short",
    status: "auctioning",
    length: 2,
    extension: ".tech",
    popularity: 98,
    isPremium: false,
    isLuxury: false,
    isShort: true,
    isBrandable: false
  },
  {
    id: 5,
    name: "sparkle.co",
    price: "$28,000",
    category: "brandable",
    status: "available",
    length: 7,
    extension: ".co",
    popularity: 76,
    isPremium: false,
    isLuxury: false,
    isShort: false,
    isBrandable: true
  },
  {
    id: 6,
    name: "forge.io",
    price: "$42,000",
    category: "premium",
    status: "available",
    length: 5,
    extension: ".io",
    popularity: 84,
    isPremium: true,
    isLuxury: false,
    isShort: true,
    isBrandable: false
  },
  {
    id: 7,
    name: "zen.co",
    price: "$65,000",
    category: "short",
    status: "available",
    length: 3,
    extension: ".co",
    popularity: 91,
    isPremium: false,
    isLuxury: false,
    isShort: true,
    isBrandable: false
  },
  {
    id: 8,
    name: "velocity.io",
    price: "$48,000",
    category: "premium",
    status: "available",
    length: 8,
    extension: ".io",
    popularity: 82,
    isPremium: true,
    isLuxury: false,
    isShort: false,
    isBrandable: false
  },
  {
    id: 9,
    name: "luna.co",
    price: "$18,000",
    category: "brandable",
    status: "available",
    length: 4,
    extension: ".co",
    popularity: 79,
    isPremium: false,
    isLuxury: false,
    isShort: true,
    isBrandable: true
  },
  {
    id: 10,
    name: "infinity.com",
    price: "$95,000",
    category: "luxury",
    status: "sold",
    length: 8,
    extension: ".com",
    popularity: 90,
    isPremium: false,
    isLuxury: true,
    isShort: false,
    isBrandable: false
  },
  {
    id: 11,
    name: "pulse.io",
    price: "$32,000",
    category: "premium",
    status: "available",
    length: 5,
    extension: ".io",
    popularity: 85,
    isPremium: true,
    isLuxury: false,
    isShort: true,
    isBrandable: false
  },
  {
    id: 12,
    name: "atlas.co",
    price: "$38,000",
    category: "premium",
    status: "available",
    length: 5,
    extension: ".co",
    popularity: 87,
    isPremium: true,
    isLuxury: false,
    isShort: true,
    isBrandable: false
  }
]